# Copyright (c) The mldsa-native project authors
# SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT

name: Isabelle proofs
permissions:
  contents: read
on:
  workflow_call:
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest
    container: makarius/isabelle:Isabelle2025-1
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build Compress session
        run: /home/isabelle/Isabelle/bin/isabelle build -D proofs/isabelle/compress
